# PyRevolut Exceptions

PyRevolut provides a number of exceptions that can be raised during the execution of the client.

---

::: pyrevolut.exceptions.common.PyRevolutBaseException

---

::: pyrevolut.exceptions.bad_request.PyRevolutBadRequest

---

::: pyrevolut.exceptions.conflict.PyRevolutConflict

---

::: pyrevolut.exceptions.forbidden.PyRevolutForbidden

---

::: pyrevolut.exceptions.internal_server_error.PyRevolutInternalServerError

---

::: pyrevolut.exceptions.invalid_environment.PyRevolutInvalidEnvironment

---

::: pyrevolut.exceptions.invalid_payload.PyRevolutInvalidPayload

---

::: pyrevolut.exceptions.method_not_allowed.PyRevolutMethodNotAllowed

---

::: pyrevolut.exceptions.network_error.PyRevolutNetworkError

---

::: pyrevolut.exceptions.not_acceptable.PyRevolutNotAcceptable

---

::: pyrevolut.exceptions.not_found.PyRevolutNotFound

---

::: pyrevolut.exceptions.server_unavailable.PyRevolutServerUnavailable

---

::: pyrevolut.exceptions.timeout_error.PyRevolutTimeoutError

---

::: pyrevolut.exceptions.too_many_requests.PyRevolutTooManyRequests

---

::: pyrevolut.exceptions.unauthorized.PyRevolutUnauthorized
